#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer 
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
sudo sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver 6515-web-01 54.198.73.120:80 check\n\tserver 6515-web-02 100.25.220.42:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
