#!/usr/bin/env bash
#This script loops from 1 to 10 displays badluck on the 
#4th iteration, goodluck on the 8th and "Best School" for others

i=0

while [ $i -lt 10 ]; do
  if [ $i -eq 3 ]; then
    echo "bad luck"
  elif [ $i -eq 7 ]; then
    echo "good luck"
  else
    echo "Best School"
  fi
  i="$((i + 1))"
done
