#!/usr/bin/env bash
#A script that gives information about the School file
file_name="school"
if test -a $file_name; then
  echo "$file_name file exists"
  if test -s $file_name; then
    echo "$file_name file is not empty"
  else
    echo "$file_name file is empty"
  fi
  if test -f $file_name; then
    echo "$file_name is a regular file"
  fi
else
  echo "$file_name file does not exist"
fi
